### ISSUE TITLE
merging windows

### ISSUE THREAD

**Issue by hrezaeianzadeh** [adamrehn/slidingwindow#1]
Can you please elaborate more on how to merge sliding windows here...

**Comment by adamrehn** [comment]
The [mergeWindows() function](https://github.com/adamrehn/slidingwindow/blob/master/slidingwindow/Merging.py) was designed primarily for stitching together the results of neural network inference passes when working with large images, but the implementation is quite generic and can be applied to any processing scenario. In essence it simply does the following:

- Allocates memory for an output dataset with the same dimensions as the input dataset
- Generates windows for the input dataset using the specified parameters (`dimOrder`, `maxWindowSize`, `overlapPercent`)
- Groups the windows into batches based on the `batchSize` parameter (this is just offered as an optional performance enhancement, and can be set to 1 if you'd like each window to be processed individually)
- Runs a user-supplied processing function over each batch, specified by the `transform` parameter
- Copies the results of the processing function into the appropriate location in the output dataset
- If a given element of the input dataset is included in multiple windows due to overlap, the value for that element in the output dataset will be the mean of the values produced by the processing function for each of the windows

The key to using the merging functionality is to specify an appropriate processing function. The function is expected to accept two arguments:

- The input dataset
- A batch of windows

The processing function will typically apply each of the windows in the batch to the dataset, and then apply whatever transformation is appropriate for your use case to the data. For example, a processing function might look like this:

```python
def process(data, batch):
    transformed = [window.apply(data) for window in batch]
    # Do something meaningful with each window of the data here
    return np.array(transformed)
```

The processing function is expected to return a NumPy array with the dimensions: `[batch, height, width, channels]`, where `batch` is the index in the batch of windows, `height` and `width` are the size of the windows in the batch, and `channels` is based on the dimensionality of the input dataset (for images, this is usually the number of colour channels, e.g. 3 channels for an RGB image.)
