### ISSUE TITLE
Is it possible to divide windows with specified width and length? 

### ISSUE THREAD

**Issue by StringBottle** [adamrehn/slidingwindow#2]
Hi, Adam 

I appreciate for your work on this useful tools.  

While using this toolbox, I found that sometimes I need to divide images with specified width and length or specified number of windows. 

Does this toolbox include related functions to do these work ? 

If not, I would like to make a pull request for it.

**Comment by adamrehn** [comment]
At the moment windows can only be generated by setting a maximum window size, and the window generation logic automatically adapts to the dataset size in order to achieve 100% coverage. If there are use cases where the specific window size or count is important and you'd like to contribute an appropriate implementation then I'd certainly be happy to accept a pull request. My suggestion would be to add one or more new functions at the bottom of [SlidingWindow.py](https://github.com/adamrehn/slidingwindow/blob/v0.0.13/slidingwindow/SlidingWindow.py) with appropriate names (e.g. `generateForWindowSize()`, `generateForNumberOfWindows()`, etc.)

**Comment by StringBottle** [comment]
@adamrehn 

I have just created pull request adding the functions that I mentioned. As far as I tested, the functions had no errors, but I think you may want to fix few lines so that it can look clean. 

If any error occurs, please let me know about it.  

Thanks!

**Comment by adamrehn** [comment]
Thanks for contributing your implementation in #4, I've now merged that into the project. Looking through your code, there was more duplication than strictly necessary, so I've refactored it in commit c3e3481, which adds some small non-breaking API changes to the existing functions and streamlines the new functions. I've also renamed the new functions to `generateRectanglarWindows()` and `generateForNumberOfWindows()` to make their purpose a little clearer, and updated their docstrings to provide a more detailed description of their use and parameters.
